services:
  - type: web
    name: ThamAI-backend
    env: node
    rootDir: backend
    region: singapore
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: ThamAI-frontend
    env: static
    rootDir: frontend
    region: singapore
    buildCommand: "echo 'Static site'"
    staticPublishPath: "."
    autoDeploy: true
